
title: yaochangbo
url: 'https://yaochangbo.github.io/'
baseurl: '/yaochangbo.github.com' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: yaochangbo
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: y-wave@163.com
phone: 010-56239885
website: yaochangbo.github.io #do not add http://
linkedin: 
github: yaochangbo
twitter: ''

